# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0002_auto_20170720_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
