# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import farm_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0003_signup_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='created_date',
            field=models.DateTimeField(default=farm_site.models.one_week_ago),
        ),
    ]
