# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0003_location_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='locations',
            field=models.ManyToManyField(to='farm_site.Location'),
        ),
        migrations.AddField(
            model_name='member',
            name='seasons',
            field=models.ManyToManyField(to='farm_site.Season'),
        ),
    ]
