# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0004_auto_20170707_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='member',
            name='seasons',
        ),
    ]
