# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0005_auto_20170707_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_site.Location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_site.Member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_site.Season')),
            ],
        ),
    ]
