# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0007_location_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_season',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
