# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0008_season_current_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
