# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0009_signup_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm_site.Season'),
        ),
    ]
