# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_site', '0011_auto_20170710_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='payment',
            field=models.CharField(choices=[('check', 'Mail check'), ('online', 'Online Bill Pay')], default='check', max_length=20),
        ),
    ]
